Repository CoderhoodFatec-2024-1/Coderhood, pull requests merged in 2024-06, with the labels that each got.

#83 Documentacao sprint 4
  documentacao/documentacao.md
  documentacao/imagens/boxplot.png
  documentacao/imagens/configuracoes_tipo_climatico.png
  documentacao/imagens/estacao_com_informacoes_adicionadas.png
  documentacao/imagens/image-1.png
  documentacao/imagens/image-10.png
  documentacao/imagens/image-12.png
  documentacao/imagens/image-13.png
  documentacao/imagens/image-14.png
  documentacao/imagens/image-15.png
  documentacao/imagens/image-16.png
  documentacao/imagens/image-17.png
  documentacao/imagens/image-18.png
  documentacao/imagens/image-19.png
  documentacao/imagens/image-2.png
  documentacao/imagens/image-21.png
  documentacao/imagens/image-22.png
  documentacao/imagens/image-23.png
  documentacao/imagens/image-3.png
  documentacao/imagens/image-4.png
  documentacao/imagens/image-5.png
  documentacao/imagens/image-6.png
  documentacao/imagens/image-7.png
  documentacao/imagens/image-8.png
  documentacao/imagens/image-9.png
  documentacao/imagens/image.png
  documentacao/manual Zeus/manual Zeus.md
Labels: documentation

#87 Teste csv resolve
  src/main/java/com/example/dadosmeteorologicos/Services/CSVResolve.java
  src/test/java/teste/CsvResolveTeste.java
  src/test/java/teste/resources/83726_SC.csv
  src/test/java/teste/resources/83781_SP.csv
  src/test/java/teste/resources/A1701_SP.csv
  src/test/java/teste/resources/A444_SP_TESTE.csv
  src/test/java/teste/resources/A728_TBT.csv
  src/test/java/teste/resources/A771_SP.csv
  src/test/java/teste/resources/A777_SC.csv
  src/test/java/teste/resources/A777_SP.csv
Labels: enhancement

#85 Teste leitor csv service
  src/main/java/com/example/dadosmeteorologicos/Services/CidadeService.java
  src/main/java/com/example/dadosmeteorologicos/Services/LeitorCsvService.java
  src/main/java/com/example/dadosmeteorologicos/controller/CidadeController.java
  src/main/java/com/example/dadosmeteorologicos/db/CidadeSQL.java
  src/main/java/com/example/dadosmeteorologicos/db/EstacaoSQL.java
  src/main/java/com/example/dadosmeteorologicos/db/LeitorCsvSQL.java
  src/main/java/com/example/dadosmeteorologicos/model/Registro.java
  src/test/java/teste/IniciaBancoTeste.java
  src/test/java/teste/LeitorCsvServiceTeste.java
  src/test/java/teste/resources/populaBanco.sql
Labels: enhancement

#90 Manual sprint 4
  documentacao/imagens/00 - Instalação_PostegreSQL.png
  documentacao/imagens/01 - Instalação_PostegreSQL.png
  documentacao/imagens/02 - Instalação_PostegreSQL.png
  documentacao/imagens/03 - Instalação_PostegreSQL.png
  documentacao/imagens/04 - Instalação_PostegreSQL.png
  documentacao/imagens/05 - Instalação_PostegreSQL.png
  documentacao/imagens/06 - Instalação_PostegreSQL.png
  documentacao/manual Zeus/manual Zeus.md
Labels: documentation

#92 Teste suspeito service
  src/main/java/com/example/dadosmeteorologicos/Services/SuspeitoService.java
  src/main/java/com/example/dadosmeteorologicos/db/SuspeitoSQL.java
  src/test/java/teste/IniciaBancoTeste.java
  src/test/java/teste/SuspeitoServiceTest.java
Labels: enhancement

#95 Teste cidade service
  src/main/java/com/example/dadosmeteorologicos/Services/CidadeService.java
  src/main/java/com/example/dadosmeteorologicos/controller/CidadeController.java
  src/main/java/com/example/dadosmeteorologicos/db/CidadeSQL.java
  src/test/java/teste/CidadeServiceTest.java
  src/test/java/teste/IniciaBancoTeste.java
  src/test/java/teste/ValorMedioServiceTest.java
Labels: enhancement

#98 Teste box plot service #68
  src/main/java/com/example/dadosmeteorologicos/Services/BoxPlotService.java
  src/main/java/com/example/dadosmeteorologicos/controller/BoxPlotController.java
  src/main/java/com/example/dadosmeteorologicos/db/BoxPlotSQL.java
  src/main/java/com/example/dadosmeteorologicos/model/BoxPlot.java
  src/main/java/com/example/dadosmeteorologicos/model/Estacao.java
  src/main/java/com/example/dadosmeteorologicos/model/EstacaoDetalhes.java
  src/main/java/com/example/dadosmeteorologicos/model/ValoresBoxPlot.java
  src/main/resources/com/example/dadosmeteorologicos/view/BoxPlot.fxml
  src/test/java/teste/BoxPlotServiceTest.java
Labels: enhancement

#101 Documentacao sprint 4
  documentacao/imagens/image-25.png
  documentacao/imagens/image-26.png
  documentacao/manual Zeus/manual Zeus.md
Labels: documentation

#102 endereco imagens
  documentacao/imagens/Configuração Zeus/00 Configuração Zeus.png
  documentacao/imagens/Configuração Zeus/01 Configuração Zeus.png
  documentacao/imagens/Instalação PostgreSQL/00 Instalação PostgreSQL.png
  documentacao/imagens/Instalação PostgreSQL/01 Instalação PostgreSQL.png
  documentacao/imagens/Instalação PostgreSQL/02 Instalação PostgreSQL.png
  documentacao/imagens/Instalação PostgreSQL/03 Instalação PostgreSQL.png
  documentacao/imagens/Instalação PostgreSQL/04 Instalação PostgreSQL.png
  documentacao/imagens/Relatorio Situação/00 Relatorio Situação.jpeg
  documentacao/imagens/Relatorio Situação/01 Relatorio Situação.png
  documentacao/imagens/Relatorio Situação/02 Relatorio Situação.jpeg
  documentacao/imagens/Relatorio Valor Medio/00 Relatorio Valor Medio.png
  documentacao/imagens/Relatorio Valor Medio/01 Relatorio Valor Medio.png
  documentacao/imagens/Relatorio Valor Medio/02 Relatorio Valor Medio.png
  documentacao/imagens/Relatorio Valor Medio/03 Relatorio Valor Medio.png
  documentacao/imagens/Relatorio Valor Medio/04 Relatorio Valor Medio.png
  documentacao/imagens/Relatorio Valor Medio/05 Relatorio Valor Medio.jpeg
  documentacao/imagens/Upload CSV/00 Upload CSV.png
  documentacao/imagens/Upload CSV/01 Upload CSV.png
  documentacao/imagens/Upload CSV/02 Upload CSV.png
  documentacao/manual Zeus/manual Zeus.md
Labels: documentation

#109 e ajustes situacao Documentacao sprint 4
  README.md
  documentacao/documentacao.md
  documentacao/imagens/02 - Upload CSV/02 Upload CSV.png
  documentacao/imagens/02 - Upload CSV/03 Upload CSV.png
  documentacao/imagens/02 - Upload CSV/04 Upload CSV.png
  documentacao/imagens/04 - Relatorio Valor Medio/05 Relatorio Valor Medio.jpeg
  documentacao/imagens/04 - Relatorio Valor Medio/07 - Relatorio Valor Medio.png
  documentacao/imagens/04 - Relatorio Valor Medio/07 Relatorio Valor Medio.jpeg
  documentacao/imagens/04 - Relatorio Valor Medio/08 Relatorio Valor Medio.png
  documentacao/imagens/04 - Relatorio Valor Medio/09 Relatorio Valor Medio.png
  documentacao/imagens/06 - Gerenciamento de Estação/04 Gerenciamento de Estacao.png
  documentacao/imagens/09 - Testes/Jacoco 1.jpg
  documentacao/imagens/09 - Testes/Jacoco 2.jpg
  documentacao/imagens/Gráfico BurnDown Sprint 4.png
  documentacao/imagens/Gráfio Burndown.jpg
  documentacao/imagens/estacao_com_informacoes_adicionadas.png
  documentacao/manual Zeus/manual Zeus.md
  src/main/java/com/example/dadosmeteorologicos/Services/SituacaoService.java
  src/main/java/com/example/dadosmeteorologicos/model/RegistroSituacao.java
Labels: bug
